### PR TITLE
Use ruff; update pre-commit config; update template CI

### LINKED ISSUE #43: Simplify linting to use only ruff
### What can be improved?

`ruff` can now do everything `black` can. We can reduce maintenance burdens by switching to pure `ruff` in the pre-commit config.

### Version

v0.2.0

### LINKED ISSUE #44: Trigger pre-commit & don't upload to codecov for internal projects
### What can be improved?

Internal projects can't use [pre-commit ci](https://pre-commit.ci/) nor [codecov](https://app.codecov.io) (they're free for public projects only).

We should trigger appropriate linting & coverage checks when the project license is set as "Not Open Source", assuming that any other license == a public project.

### Version

v0.2.0

### PR DESCRIPTION
**Pull request by brynpickering**
Fixes #43 
Fixes #44

### CODE REVIEW

**Review by mfitz — COMMENTED** [review]
- **The Black/Ruff change:** 👍  
- **The Codecov upload change:** ❓

It's possible to read the repo's visibility directly inside Actions at runtime, rather than inferring it from the presence/absence of (or contents/metadata about) a licence file. That seems like a better way to do it.

Take a look at [this example](https://github.com/arup-group/city-modelling-lab/actions/runs/11235933979/workflow) I just had a play about with.

[This](https://github.com/arup-group/city-modelling-lab/actions/runs/11235933979/job/31234954041) is what happened when I triggered it.

Screenshot 2024-10-08 at 14 06 10


Could we use this more explicit means of checking repo visibility in a conditional somewhere, either in the workflow template, or maybe even in the reusable workflow that does the codecov upload ([here](https://github.com/arup-group/actions-city-modelling-lab/blob/6c235bf7bfd7f07d7ac0180f194d4ddd77b4ddcf/.github/workflows/python-install-lint-test.yml#L84), by the looks of it - maybe there are other workflows too, I didn't check)?

**Comment by brynpickering** [comment]
Nice, definitely a better approach! I'll bake it in wherever I'm checking for the license at the moment. Probably for private vs. public (since internal == private, right?)

**Comment by brynpickering** [comment]
I have to kind of hope that the latest changes will work as expected w.r.t. codecov uploading. `github.events.repository.public` isn't available, so I've gone with `github.event.repository.visibility == 'public'`.

I've also got template linting to work properly!

**Comment by brynpickering** [comment]
@mfitz can you merge this while I'm offline, if you approve it?

**Comment by mfitz** [comment]
> Nice, definitely a better approach! I'll bake it in wherever I'm checking for the license at the moment. Probably for private vs. public (since internal == private, right?)

`internal` is private, yes. I _think_ `private` is probably for private repos that don't belong to a GitHub group/organisation, and `internal` is the organisation equivalent.

**Review by mfitz — APPROVED** [review]
👍

**Pull request merged**
